/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kasir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class KelolaUser extends javax.swing.JPanel {

    /**
     * Creates new form KelolaUser
     */
    
    private boolean editMode = false; 
    private int editId = -1; // simpan id user yg diedit
    
    public KelolaUser() {
        initComponents();
        isiComboBox();
        tampilData(); 
    }
    
    // tampilkan data user di tabel
    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Role");
        model.addColumn("Status");
        
        try (Connection conn = kasir.koneksi.dbKonek()) {
            String sql = "SELECT *FROM pengguna ORDER BY idpengguna ASC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            int no = 1;
            while (rs.next()) {
                model.addRow(new Object[]{
                    no++,
                    rs.getInt("idpengguna"),
                    rs.getString("username"),
                    rs.getString("role"),
                    rs.getString("status")
                });
            }
            tblUser.setModel(model);
            
            // sembunyikan kolom ID (jangan ditampilkan ke user)
            tblUser.getColumnModel().getColumn(1).setMinWidth(0);
            tblUser.getColumnModel().getColumn(1).setMaxWidth(0);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error tampil data: " + ex.getMessage());
        }
    }
    // isi combobox role dan status
    private void isiComboBox() {
        cbRole.removeAllItems();
        cbRole.addItem("admin");
        cbRole.addItem("kasir");
        cbRole.addItem("manager");
        
        cbStatus.removeAllItems();
        cbStatus.addItem("aktif");
        cbStatus.addItem("tidak aktif");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnback = new javax.swing.JPanel();
        pnFormUser = new javax.swing.JPanel();
        lStatus = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        lPass = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        lRole = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        btSubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pnDaftarUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btDelete = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        Batal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1720, 960));
        setPreferredSize(new java.awt.Dimension(1720, 960));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnback.setBackground(new java.awt.Color(255, 255, 255));
        pnback.setPreferredSize(new java.awt.Dimension(1740, 960));
        pnback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnFormUser.setBackground(new java.awt.Color(255, 255, 255));
        pnFormUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnFormUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lStatus.setText("Status :");
        pnFormUser.add(lStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 60, 30));

        lUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lUsername.setText("Username :");
        pnFormUser.add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lPass.setText("Password :");
        pnFormUser.add(lPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnFormUser.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 260, 60));

        tfPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnFormUser.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 260, 60));

        cbStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnFormUser.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 260, 50));

        lRole.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lRole.setText("Role : ");
        pnFormUser.add(lRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 50, -1));

        cbRole.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });
        pnFormUser.add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 260, 50));

        btSubmit.setBackground(new java.awt.Color(102, 255, 102));
        btSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSubmit.setText("SUBMIT");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });
        pnFormUser.add(btSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 310, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel10.setText("Form User");
        pnFormUser.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnback.add(pnFormUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 460, 740));

        pnDaftarUser.setBackground(new java.awt.Color(255, 255, 255));
        pnDaftarUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnDaftarUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("Daftar User");
        pnDaftarUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "ID User", "Username", "Password", "Status"
            }
        ));
        tblUser.setRowHeight(30);
        jScrollPane2.setViewportView(tblUser);

        pnDaftarUser.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1060, 550));

        btDelete.setBackground(new java.awt.Color(255, 51, 51));
        btDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        pnDaftarUser.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 110, 90, 40));

        btEdit.setBackground(new java.awt.Color(255, 255, 51));
        btEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        pnDaftarUser.add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 90, 40));

        Batal.setBackground(new java.awt.Color(102, 102, 255));
        Batal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Batal.setText("Batal");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });
        pnDaftarUser.add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 90, 40));

        pnback.add(pnDaftarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 1100, 740));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel2.setText("Kelola User");
        pnback.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        add(pnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1720, 920));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel3.setText("Kelola User");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
         int row = tblUser.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit!");
                return;
            }
            
            // ambil data dari tabel
            int id = Integer.parseInt(tblUser.getValueAt(row, 1).toString());
            String username = tblUser.getValueAt(row, 2).toString();
            String role     = tblUser.getValueAt(row, 3).toString();
            String status   = tblUser.getValueAt(row, 4).toString();
            
            // isi form
            tfUsername.setText(username);
            tfPassword.setText(""); // kosongkan (password tidak ditampilkan)
            cbRole.setSelectedItem(role);
            cbStatus.setSelectedItem(status);
            
            editMode = true;
            editId = id;
    }//GEN-LAST:event_btEditActionPerformed

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoleActionPerformed

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
            String username = tfUsername.getText().trim();
            String password = tfPassword.getText().trim();
            String role     = cbRole.getSelectedItem().toString();
            String status   = cbStatus.getSelectedItem().toString();
            
            if (username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                        "Username dan Password tidak boleh kosong!");
                return;
            }
            
            try (Connection conn = koneksi.dbKonek()) {
                if (!editMode) { 
                    // mode tambah user baru
                    String sql = "INSERT INTO pengguna (username, password, role, status) VALUES (?, ?, ?, ?)";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, username);
                    ps.setString(2, password);
                    ps.setString(3, role);
                    ps.setString(4, status);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "User berhasil ditambahkan!");
                    
                } else {
                    // mode edit user
                    String sql = "UPDATE pengguna SET username=?, password=?, role=?, status=? WHERE idpengguna=?";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, username);
                    ps.setString(2, password);
                    ps.setString(3, role);
                    ps.setString(4, status);
                    ps.setInt(5, editId);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "User berhasil diupdate!");
                    
                    editMode = false; 
                    editId = -1;
                }
                
                // reset form
                tfUsername.setText("");
                tfPassword.setText("");
                cbRole.setSelectedIndex(0);
                cbStatus.setSelectedIndex(0);
                
                tampilData(); // refresh tabel
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                ex.printStackTrace();
            }
        
    }//GEN-LAST:event_btSubmitActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
         int row = tblUser.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
                return;
            }
            
            int id = Integer.parseInt(tblUser.getValueAt(row, 1).toString());
            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Yakin ingin menghapus user ini?", 
                    "Konfirmasi Hapus", 
                    JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                try (Connection conn = koneksi.dbKonek()) {
                    String sql = "DELETE FROM pengguna WHERE idpengguna=?";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setInt(1, id);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "User berhasil dihapus!");
                    tampilData();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error hapus: " + ex.getMessage());
                }
            }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
    tfUsername.setText("");
    tfPassword.setText("");
    cbRole.setSelectedIndex(0);  
    cbStatus.setSelectedIndex(0); 
    tblUser.clearSelection();

    }//GEN-LAST:event_BatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btSubmit;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lPass;
    private javax.swing.JLabel lRole;
    private javax.swing.JLabel lStatus;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPanel pnDaftarUser;
    private javax.swing.JPanel pnFormUser;
    private javax.swing.JPanel pnback;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
