/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kasir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yaniyan
 */
public class KelolaBarang extends javax.swing.JPanel {

    private boolean editMode = false; 
    private int editId = -1;
    /**
     * Creates new form KelolaBarang
     */
    public KelolaBarang() {
        initComponents();
        tampilData();
    }
    
    // tampilkan data user di tabel
    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Kode barang");
        model.addColumn("SKU");
        model.addColumn("Nama Barang");
        model.addColumn("Kategori");
        model.addColumn("Harga Pokok");
        model.addColumn("PPN");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        model.addColumn("Satuan");
        
        try (Connection conn = kasir.koneksi.dbKonek()) {
            String sql = "SELECT *FROM barang ORDER BY kodebarang ASC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            int no = 1;
            while (rs.next()) {
                model.addRow(new Object[]{
                    no++,
                    rs.getInt("kodebarang"),
                    rs.getString("skubarang"),
                    rs.getString("nama"),
                    rs.getString("kategori"),
                    rs.getString("hargapokok"),
                    rs.getString("ppn"),
                    rs.getString("hargabarang"),
                    rs.getString("stok"),
                    rs.getString("satuan")
                });
            }
            tblBarang.setModel(model);
            
            // sembunyikan kolom ID (jangan ditampilkan ke user)
            tblBarang.getColumnModel().getColumn(1).setMinWidth(0);
            tblBarang.getColumnModel().getColumn(1).setMaxWidth(0);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error tampil data: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tKdBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tHargaPokok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tPajak = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tSKU = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tSatuan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tNamaBarang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tHargaJual = new javax.swing.JTextField();
        lbGambar = new javax.swing.JLabel();
        btPilGambar = new javax.swing.JButton();
        btTambah = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        pnDaftarBarang = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        tCari = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbfJenis = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Kelola Barang");

        pnForm.setBackground(new java.awt.Color(255, 255, 255));
        pnForm.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel2.setText("Input Barang");

        jLabel3.setText("Kode Barang");

        jLabel4.setText("Kategori");

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Harga Pokok");

        jLabel6.setText("PPN");

        jLabel7.setText("SKU Barang");

        jLabel8.setText("Satuan");

        jLabel9.setText("Nama Barang");

        jLabel10.setText("Harga Jual");

        lbGambar.setBackground(new java.awt.Color(204, 204, 204));

        btPilGambar.setText("Pilih Gambar");
        btPilGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPilGambarActionPerformed(evt);
            }
        });

        btTambah.setText("Tambah");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });

        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDelete.setText("Delete");

        btCancel.setText("Batal");

        javax.swing.GroupLayout pnFormLayout = new javax.swing.GroupLayout(pnForm);
        pnForm.setLayout(pnFormLayout);
        pnFormLayout.setHorizontalGroup(
            pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormLayout.createSequentialGroup()
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tKdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(tSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnFormLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btTambah)
                                .addGap(18, 18, 18)
                                .addComponent(btEdit)))
                        .addGap(18, 18, 18)
                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnFormLayout.createSequentialGroup()
                                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnFormLayout.createSequentialGroup()
                                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(tHargaPokok, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(tPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnFormLayout.createSequentialGroup()
                                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(tSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(tNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(tHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(266, 266, 266)
                                .addComponent(lbGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnFormLayout.createSequentialGroup()
                                .addComponent(btDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCancel)))))
                .addContainerGap(474, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btPilGambar)
                .addGap(507, 507, 507))
        );
        pnFormLayout.setVerticalGroup(
            pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tHargaPokok, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnFormLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnFormLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnFormLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnFormLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnFormLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tKdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnFormLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(lbGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btPilGambar)
                                .addGap(41, 41, 41)))
                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTambah)
                            .addComponent(btEdit)
                            .addComponent(btDelete)
                            .addComponent(btCancel))
                        .addGap(23, 23, 23))))
        );

        pnDaftarBarang.setBackground(new java.awt.Color(255, 255, 255));
        pnDaftarBarang.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel11.setText("Daftar Barang");

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No. ", "Kode Barang", "SKU ", "Nama", "Kategori", "Harga", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tblBarang);

        jLabel12.setText("Cari");

        cbfJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnDaftarBarangLayout = new javax.swing.GroupLayout(pnDaftarBarang);
        pnDaftarBarang.setLayout(pnDaftarBarangLayout);
        pnDaftarBarangLayout.setHorizontalGroup(
            pnDaftarBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDaftarBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDaftarBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDaftarBarangLayout.createSequentialGroup()
                        .addGroup(pnDaftarBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(pnDaftarBarangLayout.createSequentialGroup()
                                .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbfJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(1211, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        pnDaftarBarangLayout.setVerticalGroup(
            pnDaftarBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDaftarBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(pnDaftarBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCari)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbfJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnDaftarBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pnForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDaftarBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btPilGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPilGambarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPilGambarActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
            int row = tblBarang.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit!");
                return;
            }

            // ambil data dari tabel
            int kode = Integer.parseInt(tblBarang.getValueAt(row, 1).toString());
            String sku = tblBarang.getValueAt(row, 2).toString();
            String nama   = tblBarang.getValueAt(row, 3).toString();
            String kategori   = tblBarang.getValueAt(row, 4).toString();

            // Ganti Integer.parseInt dengan Double.parseDouble untuk nilai desimal
            double hargapokok   = Double.parseDouble(tblBarang.getValueAt(row, 5).toString());
            double ppn   = Double.parseDouble(tblBarang.getValueAt(row, 6).toString());
            double harga   = Double.parseDouble(tblBarang.getValueAt(row, 7).toString());
            int stok   = Integer.parseInt(tblBarang.getValueAt(row, 8).toString());
            
            String satuan = tblBarang.getValueAt(row, 9).toString();

            // isi form
            tKdBarang.setText(String.valueOf(kode));  // Mengubah int menjadi String
            tSKU.setText(sku);
            tNamaBarang.setText(nama);
            tHargaPokok.setText(String.valueOf(hargapokok));  // Mengubah double menjadi String
            tPajak.setText(String.valueOf(ppn));  // Mengubah double menjadi String
            tHargaJual.setText(String.valueOf(harga));  // Mengubah double menjadi String
            cbJenis.setSelectedItem(kategori);
            tSatuan.setText(satuan);
            
            editMode = true;
            editId = kode;
    }//GEN-LAST:event_btEditActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
            int kdbarang = Integer.parseInt(tKdBarang.getText().trim());
            String sku = tSKU.getText().trim();
            String nama = tNamaBarang.getText().trim();
            int hargapokok = Integer.parseInt(tHargaPokok.getText().trim());
            int ppn = Integer.parseInt(tPajak.getText().trim());
            int hargajual = Integer.parseInt(tHargaJual.getText().trim());
            String kategori    = cbJenis.getSelectedItem().toString();
            String satuan = tSatuan.getText().trim();
            
            if (nama.isEmpty() || sku.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                        "Username dan Password tidak boleh kosong!");
                return;
            }
            
            try (Connection conn = koneksi.dbKonek()) {
                if (!editMode) { 
                    // mode tambah user baru
                    String sql = "INSERT INTO barang (kodebarang, skubarang, nama, hargabarang,  kategori, hargapokok, ppn, satuan) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setInt(1, kdbarang);
                    ps.setString(2, sku);
                    ps.setString(3, nama);
                    ps.setInt(4, hargajual);
                    ps.setString(5, kategori);
                    ps.setInt(6, hargapokok);
                    ps.setInt(7, ppn);
                    ps.setString(8, satuan);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Barang berhasil ditambahkan!");
                    
                } else {
                    // mode edit user
                    String sql = "UPDATE barang SET  nama=?, hargabarang=?,  kategori=?, hargapokok=?, ppn=?, satuan=? WHERE kodebarang=?";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, nama);
                    ps.setInt(2, hargajual);
                    ps.setString(3, kategori);
                    ps.setInt(4, hargapokok);
                    ps.setInt(5, ppn);
                    ps.setString(6, satuan);
                    ps.setInt(7, editId);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Barang berhasil diupdate!");
                    
                    editMode = false; 
                    editId = -1;
                }
                
                // reset form
                tNamaBarang.setText("");
                tHargaJual.setText("");
                tHargaPokok.setText("");
                tPajak.setText("");
                tSatuan.setText("");
                tKdBarang.setText("");
                tSKU.setText("");
                cbJenis.setSelectedIndex(0);
               
                
                tampilData(); // refresh tabel
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                ex.printStackTrace();
            }
    }//GEN-LAST:event_btTambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btPilGambar;
    private javax.swing.JButton btTambah;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbfJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGambar;
    private javax.swing.JPanel pnDaftarBarang;
    private javax.swing.JPanel pnForm;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tHargaJual;
    private javax.swing.JTextField tHargaPokok;
    private javax.swing.JTextField tKdBarang;
    private javax.swing.JTextField tNamaBarang;
    private javax.swing.JTextField tPajak;
    private javax.swing.JTextField tSKU;
    private javax.swing.JTextField tSatuan;
    private javax.swing.JTable tblBarang;
    // End of variables declaration//GEN-END:variables
}
