/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kasir;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yaniyan
 */
public class KelolaKeuangan extends javax.swing.JPanel {

    /**
     * Creates new form LaporanTransaksi
     */
    public KelolaKeuangan() {
        initComponents();
        loadDataKeuangan();
                    jdcTanggal.setDate(new java.util.Date());
                    setFilterDefault();

    }
boolean isEditMode = false; 
int selectedId = -1; // untuk simpan idkeuangan yang dipilih
// taruh di atas class
private java.util.List<Integer> idList = new ArrayList<>(); // buat simpan id

private void loadDataKeuangan() {
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // tabel tidak bisa diubah langsung
        }
    };

    model.addColumn("No");
    model.addColumn("Jenis Keuangan");
    model.addColumn("Masuk");
    model.addColumn("Keluar");
    model.addColumn("Tanggal");

    try (Connection conn = koneksi.dbKonek()) {
String sql = "SELECT idkeuangan, jeniskeuangan, masuk, keluar, tanggal "
           + "FROM keuangan "
           + "WHERE tanggal::date >= date_trunc('month', CURRENT_DATE) "
           + "AND tanggal::date < (date_trunc('month', CURRENT_DATE) + interval '1 month') "
           + "ORDER BY tanggal DESC";
PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        idList.clear(); // reset dulu list id
        int no = 1;

        while (rs.next()) {
            idList.add(rs.getInt("idkeuangan")); // simpan ID ke list
            model.addRow(new Object[]{
                no++, // nomor urut
                rs.getString("jeniskeuangan"),
                rs.getDouble("masuk"),
                rs.getDouble("keluar"),
                rs.getDate("tanggal")
            });
        }

        tblKeuangan.setModel(model);

        // atur lebar kolom No biar kecil
        tblKeuangan.getColumnModel().getColumn(0).setPreferredWidth(40);
        tblKeuangan.getColumnModel().getColumn(0).setMaxWidth(40);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }
}
private void setFilterDefault() {
    Calendar cal = Calendar.getInstance();

    // awal bulan
    cal.set(Calendar.DAY_OF_MONTH, 1);
    jdcStart.setDate(cal.getTime());

    // akhir bulan
    cal.set(Calendar.DAY_OF_MONTH, cal.getActualMaximum(Calendar.DAY_OF_MONTH));
    jdcEnd.setDate(cal.getTime());
}


private void clearForm() {
    txtJenis.setText("");
    txtMasuk.setText("");
    txtKeluar.setText("");
    jdcTanggal.setDate(null);

    isEditMode = false;
    selectedId = -1;
    tblKeuangan.clearSelection();
}


/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnFormUser = new javax.swing.JPanel();
        jdcTanggal = new com.toedter.calendar.JDateChooser();
        lUsername = new javax.swing.JLabel();
        lPass = new javax.swing.JLabel();
        txtJenis = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMasuk = new javax.swing.JTextField();
        lPass1 = new javax.swing.JLabel();
        txtKeluar = new javax.swing.JTextField();
        lPass2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        pnDaftarUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jdcStart = new com.toedter.calendar.JDateChooser();
        jdcEnd = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        btnFilter = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeuangan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1740, 960));

        pnFormUser.setBackground(new java.awt.Color(255, 255, 255));
        pnFormUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnFormUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnFormUser.add(jdcTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 340, 60));

        lUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lUsername.setText("Tanggal:");
        pnFormUser.add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lPass.setText("Jenis Keuangan:");
        pnFormUser.add(lPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txtJenis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnFormUser.add(txtJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 340, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel10.setText("Kelola Keuangan");
        pnFormUser.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtMasuk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnFormUser.add(txtMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 340, 60));

        lPass1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lPass1.setText("Masuk:");
        pnFormUser.add(lPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        txtKeluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeluarActionPerformed(evt);
            }
        });
        pnFormUser.add(txtKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 340, 60));

        lPass2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lPass2.setText("Keluar:");
        pnFormUser.add(lPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        btnSubmit.setBackground(new java.awt.Color(0, 255, 51));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSubmit.setText("SUBMIT ");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        pnFormUser.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 320, 50));

        pnDaftarUser.setBackground(new java.awt.Color(255, 255, 255));
        pnDaftarUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnDaftarUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("Daftar Keuangan");
        pnDaftarUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnDaftarUser.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 120, 40));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnDaftarUser.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, 120, 40));
        pnDaftarUser.add(jdcStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, 40));
        pnDaftarUser.add(jdcEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 150, 40));

        jLabel2.setText("SAMPAI");
        pnDaftarUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        btnFilter.setText("FILTER");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        pnDaftarUser.add(btnFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 120, 40));

        btnReset.setText("REFRESH");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        pnDaftarUser.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 120, 40));

        tblKeuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "JenisKeuangan", "Masuk", "Keluar", "Total"
            }
        ));
        tblKeuangan.setRowHeight(25);
        tblKeuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKeuanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKeuangan);

        pnDaftarUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 1040, 520));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel3.setText("Kelola Keungan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnFormUser, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(pnDaftarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 1142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnDaftarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(pnFormUser, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeluarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
int row = tblKeuangan.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu di tabel!");
        return;
    }

    // set mode edit
    isEditMode = true;

    // isi field dari tabel
    String jenis = tblKeuangan.getValueAt(row, 1).toString();
    String masuk = tblKeuangan.getValueAt(row, 2).toString();
    String keluar = tblKeuangan.getValueAt(row, 3).toString();
    Object tgl = tblKeuangan.getValueAt(row, 4);

    txtJenis.setText(jenis);
    txtMasuk.setText(masuk);
    txtKeluar.setText(keluar);

    if (tgl != null) {
        if (tgl instanceof java.sql.Date || tgl instanceof java.util.Date) {
            jdcTanggal.setDate((java.util.Date) tgl);
        }
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
   java.util.Date tglMulai = jdcStart.getDate();
    java.util.Date tglSelesai = jdcEnd.getDate();

    if (tglMulai == null || tglSelesai == null) {
        JOptionPane.showMessageDialog(this, "Pilih tanggal mulai dan tanggal selesai!");
        return;
    }

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Jenis Keuangan");
    model.addColumn("Masuk");
    model.addColumn("Keluar");
    model.addColumn("Tanggal");

    idList.clear(); // reset list ID

    try (Connection conn = koneksi.dbKonek()) {
        String sql = "SELECT idkeuangan, jeniskeuangan, masuk, keluar, tanggal "
                   + "FROM keuangan "
                   + "WHERE tanggal BETWEEN ? AND ? "
                   + "ORDER BY tanggal DESC";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setDate(1, new java.sql.Date(tglMulai.getTime()));
        pst.setDate(2, new java.sql.Date(tglSelesai.getTime()));

        ResultSet rs = pst.executeQuery();
        int no = 1;
        while (rs.next()) {
            idList.add(rs.getInt("idkeuangan"));
            model.addRow(new Object[]{
                no++,
                rs.getString("jeniskeuangan"),
                rs.getDouble("masuk"),
                rs.getDouble("keluar"),
                rs.getDate("tanggal")
            });
        }

        tblKeuangan.setModel(model);

        // biar kolom No kecil
        tblKeuangan.getColumnModel().getColumn(0).setPreferredWidth(40);
        tblKeuangan.getColumnModel().getColumn(0).setPreferredWidth(40);
        tblKeuangan.getColumnModel().getColumn(0).setMaxWidth(40);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal filter data: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
   String jenis = txtJenis.getText();
        double masuk = Double.parseDouble(txtMasuk.getText());
        double keluar = Double.parseDouble(txtKeluar.getText());
        java.util.Date utilDate = jdcTanggal.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        try (Connection conn = koneksi.dbKonek()) {
            if (isEditMode) {
                // UPDATE
                String sql = "UPDATE keuangan SET jeniskeuangan=?, masuk=?, keluar=?, tanggal=? WHERE idkeuangan=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, jenis);
                pst.setDouble(2, masuk);
                pst.setDouble(3, keluar);
                pst.setDate(4, sqlDate);
                pst.setInt(5, selectedId);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
                isEditMode = false; // reset mode
                selectedId = -1;
            } else {
                // INSERT
                String sql = "INSERT INTO keuangan (jeniskeuangan, masuk, keluar, tanggal) VALUES (?,?,?,?)";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, jenis);
                pst.setDouble(2, masuk);
                pst.setDouble(3, keluar);
                pst.setDate(4, sqlDate);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
            }
            // refresh table setelah insert / update
            loadDataKeuangan();
            clearForm();
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void tblKeuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKeuanganMouseClicked
         int row = tblKeuangan.getSelectedRow();
    if (row != -1) {
        // simpan id keuangan yang dipilih
        selectedId = idList.get(row);
    }
    }//GEN-LAST:event_tblKeuanganMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
 int row = tblKeuangan.getSelectedRow();
    if (row == -1 || selectedId == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang mau dihapus!");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.YES_OPTION) {
        try (Connection conn = koneksi.dbKonek()) {
            String sql = "DELETE FROM keuangan WHERE idkeuangan=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, selectedId);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            loadDataKeuangan();
            clearForm();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error hapus: " + e.getMessage());
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
clearForm();        // TODO add your handling code here:
 loadDataKeuangan();  // panggil ulang fungsi load semua data
setFilterDefault();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcEnd;
    private com.toedter.calendar.JDateChooser jdcStart;
    private com.toedter.calendar.JDateChooser jdcTanggal;
    private javax.swing.JLabel lPass;
    private javax.swing.JLabel lPass1;
    private javax.swing.JLabel lPass2;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPanel pnDaftarUser;
    private javax.swing.JPanel pnFormUser;
    private javax.swing.JTable tblKeuangan;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtKeluar;
    private javax.swing.JTextField txtMasuk;
    // End of variables declaration//GEN-END:variables
}
