/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package kasir;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.*;
import java.awt.*;
import java.util.*;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
/**
 *
 * @author yaniyan
 */
public class PopupDetailTransaksi extends javax.swing.JDialog {

    /**
     * Creates new form PopupDetailTransaksi
     */
    public PopupDetailTransaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        header();
    }

    private void header(){
     JTableHeader header = tblDetail.getTableHeader();
header.setOpaque(false); // Matikan transparansi bawaan
header.setPreferredSize(new Dimension(header.getWidth(), 40)); // 30 = tinggi header (px)

header.setBackground(new java.awt.Color(5,69,162)); // Warna #2c3e50
header.setForeground(Color.WHITE); // Warna font putih
header.setFont(new Font("Segoe UI",Font.BOLD, 14)); // Font tebal

// Nonaktifkan UI bawaan Nimbus supaya warna tidak di-override
header.setDefaultRenderer((table, value, isSelected, hasFocus, row, column) -> {
    JLabel label = new JLabel(value.toString());
    label.setOpaque(true);
    label.setBackground(new java.awt.Color(5,69,162));
    label.setForeground(Color.WHITE);
    label.setFont(new Font("Segoe UI", Font.BOLD, 15));
    label.setBorder(UIManager.getBorder("TableHeader.cellBorder"));
    label.setHorizontalAlignment(SwingConstants.LEFT);
    return label;
});
    }
    private int idTransaksi;

    public PopupDetailTransaksi(java.awt.Frame parent, boolean modal, int idTransaksi) {
        super(parent, modal);
        initComponents();
        this.idTransaksi = idTransaksi;
        loadDetailTransaksi();
    }
    
    private void loadDetailTransaksi() {
        try (Connection conn = koneksi.dbKonek()) {
            // === Header Transaksi ===
            String sqlTrans = "SELECT * FROM transaksi WHERE idtransaksi = ?";
            PreparedStatement pst = conn.prepareStatement(sqlTrans);
            pst.setInt(1, idTransaksi);
            ResultSet rs = pst.executeQuery();
           if (rs.next()) {
    lblKode.setText("Detail Transaksi Dari: " + rs.getString("notransaksi"));
    lblKasir.setText("Nama Kasir: " + rs.getString("namapengguna"));
    lblTanggal.setText("Tanggal: " + rs.getTimestamp("tgl_transaksi").toString());
    lblSubtotal.setText("Subtotal: Rp " + rs.getBigDecimal("subtotal").toString());
    lblDiskon.setText("Diskon dalam persen: " + rs.getBigDecimal("diskon").toString());
    lblGrandTotal.setText("Total Akhir: Rp " + rs.getBigDecimal("grand_total").toString());
    lblMetode.setText("Metode: " + rs.getString("metodepembayaran"));
}

            // === Detail Barang ===
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"Nama Barang", "Jumlah", "Harga", "Subtotal"}, 0
            );
            String sqlDetail = "SELECT namabarang, jumlah, harga, subtotal FROM detailtransaksi WHERE idtransaksi = ?";
            pst = conn.prepareStatement(sqlDetail);
            pst.setInt(1, idTransaksi);
            rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("namabarang"),
                    rs.getInt("jumlah"),
                    rs.getBigDecimal("harga"),
                    rs.getBigDecimal("subtotal")
                });
            }
            tblDetail.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal load detail: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblKode = new javax.swing.JLabel();
        lblKasir = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        lblMetode = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(997, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sis.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 189, -1));

        lblKode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKode.setText("KODE : ");
        jPanel1.add(lblKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 494, 43));

        lblKasir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKasir.setText("Nama Kasir:");
        jPanel1.add(lblKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 494, 43));

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTanggal.setText("Tanggal :");
        jPanel1.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 494, 43));

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtotal.setText("Subtotal");
        jPanel1.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 494, 43));

        lblDiskon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiskon.setText("Diskon");
        jPanel1.add(lblDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 494, 43));

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGrandTotal.setText("GrandTotal");
        jPanel1.add(lblGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 494, 43));

        lblMetode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMetode.setText("Metode");
        jPanel1.add(lblMetode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 494, 43));

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetail.setRowHeight(30);
        jScrollPane1.setViewportView(tblDetail);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 570, 220));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel2.setText("Sakpore");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 200, 100));

        btnCetak.setBackground(new java.awt.Color(0, 102, 102));
        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jPanel1.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 723, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
           // TODO add your handling code here:
             try {
        // === Dialog pilih lokasi simpan ===
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Simpan Laporan Transaksi");
        
        // default nama file
        String defaultFileName = "Transaksi_" + lblKode.getText().replace("Detail Transaksi Dari: ", "") + ".pdf";
        fileChooser.setSelectedFile(new java.io.File(defaultFileName));
        
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            
            // pastikan ekstensinya .pdf
            String fileName = fileToSave.getAbsolutePath();
            if (!fileName.toLowerCase().endsWith(".pdf")) {
                fileName += ".pdf";
            }

            // === Buat dokumen PDF ===
            com.itextpdf.text.Document document = new com.itextpdf.text.Document();
            com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(fileName));
            document.open();

            // Judul
            com.itextpdf.text.Font fontTitle = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 18, com.itextpdf.text.Font.BOLD);
            document.add(new com.itextpdf.text.Paragraph("Sakpore - Detail Transaksi", fontTitle));
            document.add(new com.itextpdf.text.Paragraph(" "));

            // Info transaksi
            document.add(new com.itextpdf.text.Paragraph(lblKode.getText()));
            document.add(new com.itextpdf.text.Paragraph(lblKasir.getText()));
            document.add(new com.itextpdf.text.Paragraph(lblTanggal.getText()));
            document.add(new com.itextpdf.text.Paragraph(lblSubtotal.getText()));
            document.add(new com.itextpdf.text.Paragraph(lblDiskon.getText()));
            document.add(new com.itextpdf.text.Paragraph(lblGrandTotal.getText()));
            document.add(new com.itextpdf.text.Paragraph(lblMetode.getText()));
            document.add(new com.itextpdf.text.Paragraph(" "));

            // Detail Barang (tabel)
            com.itextpdf.text.pdf.PdfPTable table = new com.itextpdf.text.pdf.PdfPTable(4);
            table.addCell("Nama Barang");
            table.addCell("Jumlah");
            table.addCell("Harga");
            table.addCell("Subtotal");

            for (int i = 0; i < tblDetail.getRowCount(); i++) {
                table.addCell(tblDetail.getValueAt(i, 0).toString());
                table.addCell(tblDetail.getValueAt(i, 1).toString());
                table.addCell(tblDetail.getValueAt(i, 2).toString());
                table.addCell(tblDetail.getValueAt(i, 3).toString());
            }

            document.add(table);
            document.close();

            JOptionPane.showMessageDialog(this, "PDF berhasil disimpan di: " + fileName);
            
            // === Opsional: langsung buka file setelah disimpan ===
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(new java.io.File(fileName));
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal mencetak: " + e.getMessage());
    }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupDetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupDetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupDetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupDetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopupDetailTransaksi dialog = new PopupDetailTransaksi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblKasir;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblMetode;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTable tblDetail;
    // End of variables declaration//GEN-END:variables
}
